<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <PublishAot>true</PublishAot>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <SelfContained>true</SelfContained>
    <NoWarn>FBERTTOK001</NoWarn> <!-- Experimental FastBertTokenizer features -->
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="FastBertTokenizer" />
    <ProjectReference Include="../FastBertTokenizer/FastBertTokenizer.csproj" />
  </ItemGroup>

</Project>
