name: Benchmark

on:
  workflow_dispatch:
  push:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        lfs: true
    - uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - uses: dotnet/nbgv@v0.4
      id: nbgv

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          src/HuggingfaceTokenizer/RustLib
    - run: cargo build --release
      working-directory: src/HuggingfaceTokenizer/RustLib

    - run: dotnet run -c Release -f net6.0
      working-directory: src/Benchmarks
