name: CI

on:
  workflow_call:
    inputs:
      build-ref:
        required: true
        type: string
  workflow_dispatch:
  push:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        lfs: true
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - uses: dotnet/nbgv@v0.4
      id: nbgv

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          src/HuggingfaceTokenizer/RustLib
    - run: cargo build --release
      working-directory: src/HuggingfaceTokenizer/RustLib

    # Remove the html head with the logo from README for nupkg
    - id: clean-readme
      uses: sean0x42/markdown-extract@v2
      with:
        file: README.md
        pattern: 'FastBertTokenizer'
    - uses: "DamianReeves/write-file-action@master"
      with:
        path: README.md
        write-mode: overwrite
        contents: ${{ steps.clean-readme.outputs.markdown }}

    - run: dotnet restore /p:ContinuousIntegrationBuild=true
    - run: dotnet build -c Release --no-restore /p:ContinuousIntegrationBuild=true

    - run: >
        dotnet test
        -c Release --no-restore --no-build
        /p:ContinuousIntegrationBuild=true
        --collect:"XPlat Code Coverage"
        --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"
        --
        RunConfiguration.CollectSourceInformation=true

    - name: Upload coverage reports to Codecov
      if: ${{ env.CODECOV_TOKEN }}
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - run: dotnet pack -c Release --no-restore --no-build /p:ContinuousIntegrationBuild=true
    - uses: actions/upload-artifact@v3
      with:
        name: FastBertTokenizer-nupkg-${{ steps.nbgv.outputs.Version }}
        path: bin/Packages/Release/**/*
